# Generated by Django 3.1 on 2024-04-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='photos/books')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('publicate_date', models.DateField()),
                ('pages', models.IntegerField()),
                ('language', models.CharField(default='english', max_length=15)),
                ('author', models.CharField(max_length=80)),
                ('publisher', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('format', models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('audio', 'Audio')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('genre', models.ManyToManyField(to='product.Genre')),
            ],
        ),
    ]
