# Generated by Django 5.0.4 on 2024-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0005_auto_20240430_1320'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookcart',
            constraint=models.UniqueConstraint(fields=('cart', 'book'), name='unique_book_in_cart'),
        ),
    ]
