# Generated by Django 5.0.4 on 2024-05-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_bookfacture_facture_bookfacture_facture_and_more'),
        ('product', '0006_alter_book_id_alter_genre_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookfacture',
            name='unique_book_in_Facture',
        ),
        migrations.AddConstraint(
            model_name='bookfacture',
            constraint=models.UniqueConstraint(fields=('facture', 'book'), name='unique_book_in_Facture'),
        ),
    ]
